@HostAddress = https://localhost:5001/api/customer

POST {{HostAddress}}/addrange
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjAiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9lbWFpbGFkZHJlc3MiOiJhZG1pbkBnbWFpbC5jb20iLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJhZG1pbiIsImV4cCI6MTY4NzA2NDkzMCwiaXNzIjoiRmFrZUlzc3VlciIsImF1ZCI6IkZha2VBdWRpZW5jZSJ9.PwuD9ONMJPx5KJ503yAMYojF7apCcoXrSiKyXwDVSBU

{
  "CustomerDtos": [
  {
    "fullName": "Colet Rossbrook",
    "email": "crossbrook0@themeforest.net"
  }, {
    "fullName": "Lonni Pierrepoint",
    "email": "lpierrepoint1@examiner.com"
  }, {
    "fullName": "Cathrin O'Driscoll",
    "email": "codriscoll2@amazonaws.com"
  }, {
    "fullName": "Base Crilley",
    "email": "bcrilley3@cyberchimps.com"
  }, {
    "fullName": "Emelita Todari",
    "email": "etodari4@liveinternet.ru"
  }, {
    "fullName": "Myer Wasselin",
    "email": "mwasselin5@php.net"
  }, {
    "fullName": "Christean Matanin",
    "email": "cmatanin6@squarespace.com"
  }, {
    "fullName": "Gabriello Heakey",
    "email": "gheakey7@hatena.ne.jp"
  }, {
    "fullName": "Danya Woodard",
    "email": "dwoodard8@dot.gov"
  }, {
    "fullName": "Aleen Tilt",
    "email": "atilt9@i2i.jp"
  }, {
    "fullName": "Margareta Baugh",
    "email": "mbaugha@ucla.edu"
  }, {
    "fullName": "Dulce Alner",
    "email": "dalnerb@gmpg.org"
  }, {
    "fullName": "Towny Hargreves",
    "email": "thargrevesc@bandcamp.com"
  }, {
    "fullName": "Fran Porritt",
    "email": "fporrittd@sciencedirect.com"
  }, {
    "fullName": "Carlos Ceccoli",
    "email": "cceccolie@multiply.com"
  }, {
    "fullName": "Harriott Di Filippo",
    "email": "hdif@instagram.com"
  }, {
    "fullName": "Jermaine Farres",
    "email": "jfarresg@ebay.co.uk"
  }, {
    "fullName": "Ronnica Belliss",
    "email": "rbellissh@globo.com"
  }, {
    "fullName": "Gunter While",
    "email": "gwhilei@163.com"
  }, {
    "fullName": "Gerrilee Lynch",
    "email": "glynchj@youtube.com"
  }, {
    "fullName": "Paulette Robus",
    "email": "probusk@usnews.com"
  }, {
    "fullName": "Terrijo Wisdish",
    "email": "twisdishl@friendfeed.com"
  }, {
    "fullName": "Jasmin Butson",
    "email": "jbutsonm@bravesites.com"
  }, {
    "fullName": "Odo Forber",
    "email": "oforbern@examiner.com"
  }, {
    "fullName": "Morris Wayt",
    "email": "mwayto@paypal.com"
  }, {
    "fullName": "Emlynne Leadston",
    "email": "eleadstonp@desdev.cn"
  }, {
    "fullName": "Sigismondo Monro",
    "email": "smonroq@uiuc.edu"
  }, {
    "fullName": "Teodoor Tocknell",
    "email": "ttocknellr@fda.gov"
  }, {
    "fullName": "Nathalie Gilbert",
    "email": "ngilberts@simplemachines.org"
  }, {
    "fullName": "Glyn Judson",
    "email": "gjudsont@devhub.com"
  }]
}

###

GET {{HostAddress}}
Accept: application/json
