@HostAddress = https://localhost:5001/api/shop

POST {{HostAddress}}/addrange
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjAiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9lbWFpbGFkZHJlc3MiOiJhZG1pbkBnbWFpbC5jb20iLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJhZG1pbiIsImV4cCI6MTY4NzA2NDkzMCwiaXNzIjoiRmFrZUlzc3VlciIsImF1ZCI6IkZha2VBdWRpZW5jZSJ9.PwuD9ONMJPx5KJ503yAMYojF7apCcoXrSiKyXwDVSBU

{
  "ShopDtos": [
    {
      "Name": "Long Chau Medicine",
      "Location": "Ba Đình Hà Nội"
    },
    {
      "Name": "Pharmacity",
      "Location": "Tp HCM"
    },
    {
      "Name": "An Khang Medicine",
      "Location": "Đà Nẵng"
    }
  ]
}