@HostAddress = https://localhost:5001/api/shop

POST {{HostAddress}}/addrange
Content-Type: application/json

{
  "ShopDtos": [
    {
      "Name": "Long Chau Medicine",
      "Location": "Ba Đình Hà Nội"
    },
    {
      "Name": "Pharmacity",
      "Location": "Tp HCM"
    },
    {
      "Name": "An Khang Medicine",
      "Location": "Đà Nẵng"
    }
  ]
}